### ISSUE TITLE
Cannot catch the typing 

### ISSUE THREAD

**Issue by 0dd** [SXKDZ/linggle_alfred#1]
<img width="605" alt="Screen Shot 2019-08-29 at 1 24 51 PM" src="https://user-images.githubusercontent.com/14125860/63912773-96f7bc80-ca60-11e9-9c2b-afdd0f2410fb.png">
<img width="605" alt="Screen Shot 2019-08-29 at 1 24 59 PM" src="https://user-images.githubusercontent.com/14125860/63912774-97905300-ca60-11e9-8258-6fc9ccc83d56.png">
<img width="605" alt="Screen Shot 2019-08-29 at 1 25 09 PM" src="https://user-images.githubusercontent.com/14125860/63912775-97905300-ca60-11e9-876d-097920152a35.png">
When if enter the linggle typing mode, it just cannnot catch my typing, is it the setting with my alfred not captatible with this?

**Comment by 0dd** [comment]
I have python2 in build and requests already 
<img width="762" alt="Screen Shot 2019-08-29 at 1 28 54 PM" src="https://user-images.githubusercontent.com/14125860/63912916-f950bd00-ca60-11e9-8b9c-0c416888ec4e.png">

**Comment by SXKDZ** [comment]
I implement this plugin in Python 3. It seems that the program exits when you type the commands. Would you please just upgrade your Python and try again?

**Comment by 0dd** [comment]
I believe I have installed python3 also, it still did not work as expect.

Another thing is about I query the json directly bymy own python program, it also do not work well either 
<img width="1344" alt="Screen Shot 2019-09-05 at 12 06 09 AM" src="https://user-images.githubusercontent.com/14125860/64272043-1b6ea180-cf71-11e9-949b-71eda83b00e3.png">
![Screen Shot 2019-09-05 at 12 03 07 AM](https://user-images.githubusercontent.com/14125860/64272044-1c073800-cf71-11e9-9a14-b3f8f67d22ea.png)

Is there any other thing that I need to consider about?

**Comment by SXKDZ** [comment]
I believe the two outputs are consistent with the behavior when you type the two words in Linggle website. It seems that feeding a single word to Linggle receives no results so you may need to query some more complex phrases. BTW, when you input a single word like that, can your Alfred show a "Visit Linggle" bar? If it doesn't, I suspect that there must be something wrong with Alfred itself as the Python script runs as expected...

**Comment by liqilei** [comment]
Hi, I also meet the same issue. Please can I ask if you have found any solution for this problem.

**Comment by SXKDZ** [comment]
> Hi, I also meet the same issue. Please can I ask if you have found any solution for this problem.

Have you tried the newest commit version?

**Comment by liqilei** [comment]
Thanks for your reply. 
I'm using the latest version (v1.2). 
My Alfred version is 4.3.4 [1229]. 
My python version is 3.8.4 with the requests version of 2.25.1. 
Also, I attach the screenshots for the issue and my config. 
<img width="562" alt="WX20210629-161852@2x" src="https://user-images.githubusercontent.com/30772675/123824829-47050d80-d8f6-11eb-97a6-d0d631f06cb5.png">
<img width="782" alt="WX20210629-161904@2x" src="https://user-images.githubusercontent.com/30772675/123824836-48363a80-d8f6-11eb-8079-70d967098473.png">

**Comment by SXKDZ** [comment]
> Thanks for your reply.
> I'm using the latest version (v1.2).
> My Alfred version is 4.3.4 [1229].
> My python version is 3.8.4 with the requests version of 2.25.1.
> Also, I attach the screenshots for the issue and my config.
> <img alt="WX20210629-161852@2x" width="562" src="https://user-images.githubusercontent.com/30772675/123824829-47050d80-d8f6-11eb-97a6-d0d631f06cb5.png">
> <img alt="WX20210629-161904@2x" width="782" src="https://user-images.githubusercontent.com/30772675/123824836-48363a80-d8f6-11eb-8079-70d967098473.png">

Thanks for your detailed information! From your screenshot I guess that the python script you run exits abnormally. 
I find that I have made a mistake in my reply to 0dd. The Alfred workflow Python framework only works for **Python 2**. Therefore, you have to make sure in your environment `python` links to Python 2.

You can manually test the core functionality using the following snippet:
```
import sys
import json
import time
import requests

if __name__ == '__main__':
    s = requests.Session()

    query = 'apple'
    query_load = requests.utils.quote(query)

    answer = s.get('https://linggle.com/api/ngram/{}'.format(query_load)).json()
    if len(answer['ngrams']) == 0:
        print('No results!')
    else:
        total = 0
        for item in answer['ngrams']:
            total += item[1]
        
        for item in answer['ngrams'][:20]:
            phrase = item[0]
            subtitle = '{:.2f}% | {}'.format(float(item[1]) * 100 / total, item[1])
            print(query, subtitle)
```
which should give output like 
```
('apple', '100.00% | 6878789')
```
```

**Comment by liqilei** [comment]
Many thanks for your reply. 

Indeed, this issues was caused by the python version incompatibility. 

Based on your helpful suggestion, I managed to solve this problem by setting the workflow interpreter to my python2 env.

Regards 
<img width="782" alt="image" src="https://user-images.githubusercontent.com/30772675/125179898-41a79d00-e1eb-11eb-9b32-b0fd73ef0446.png">

**Comment by SXKDZ** [comment]
> Many thanks for your reply.
> 
> Indeed, this issues was caused by the python version incompatibility.
> 
> Based on your helpful suggestion, I managed to solve this problem by setting the workflow interpreter to my python2 env.
> 
> Regards
> <img alt="image" width="782" src="https://user-images.githubusercontent.com/30772675/125179898-41a79d00-e1eb-11eb-9b32-b0fd73ef0446.png">

Happy to see you have resolved the problem!
